### ISSUE TITLE
In code editor text is not visible properly 

### ISSUE THREAD

**Issue by priyanka0906** [Algo-Phantoms/Algo-Phantoms-Android#10]
**Explanation**
In code editor text is not visible properly 

**Possible solution**
1. either color can be changed in  codeFragment.kt 
2. or  the background color can be chnaged  in fragment_code.xml

@dheerajkotwani  if it seems valid ..please assign this to me.

**Comment by shreyadubey0902** [comment]
Hey, I am a participant at GSSoc'21 , I am really interested to contribute to this issue can you assign me?

**Comment by priyanka0906** [comment]
> Hey, I am a participant at GSSoc'21 , I am really interested to contribute to this issue can you assign me?

@shreyadubey0902  I have created a PR for this..
