### ISSUE TITLE
Adding Splash Screen Feature 

### ISSUE THREAD

**Issue by Shreyash41** [Algo-Phantoms/Algo-Phantoms-Android#11]
### Explanation
Adding Modern Splash Screen Feature in Algo-Phantoms android.

@dheerajkotwani I would like to Contribute to this Feature under GSSOC'21, please assign this to me.

**Comment by pallavidhere23** [comment]
I can fix this issue.Please assign me this issue under GSSOC'2021.

**Comment by rahulsain** [comment]
If @Shreyash41 is currently not working on this issue, can you please assign me?

**Comment by Shreyash41** [comment]
@dheerajkotwani Sir, I am currently working on this issue, due to my mid - sem exams I haven't unable to complete this but I complete it ASAP.
