### ISSUE TITLE
User login and Registration

### ISSUE THREAD

**Issue by etamys** [Algo-Phantoms/Algo-Phantoms-Android#16]

**Comment by Starboww** [comment]
We can use firebase for user login and registration. Can you assign me this issue under GSSOC 21

**Comment by tanishq-123** [comment]
Can you please assign this issue to me

**Comment by Shulabh-968026** [comment]
I would like to work on it.Can I woek on it.

**Comment by dheerajkotwani** [comment]
@Starboww will you be working on the issue?

**Comment by Starboww** [comment]
Ya, Sure

**Comment by SanjayDevTech** [comment]
@dheerajkotwani Is anyone working on this issue... I need this pr to be merged for the profile fragment..
If no one is active, I can add the login feature : )
