### ISSUE TITLE
When you try to login or signup the text you enter isn't visible

### ISSUE THREAD

**Issue by jonathanalvares9009** [Algo-Phantoms/Algo-Phantoms-Android#5]
I would like to solve this issue by increasing the contrast between the background and foreground. Can the maintainer assign me this issue?

**Comment by adiig7** [comment]
@dheerajkotwani  can I work on this?

**Comment by sudhansukinng** [comment]
@jonathanalvares9009 please assign this issue to me under GSSOC'21.

**Comment by jonathanalvares9009** [comment]
> @jonathanalvares9009 please assign this issue to me under GSSOC'21.

I'm not the mentor. I'm also a participant

**Comment by sudhansukinng** [comment]
@jonathanalvares9009, sorry, as i am new to open source, I was unaware of creating issue.

**Comment by Kaustubh-Umbarkar** [comment]
@dheerajkotwani I can help in solving this issue can you assign me this issue

**Comment by naman5665** [comment]
Hey @dheerajkotwani Can I work on this issue ??
